# Mimir single-tenant local dev config
multitenancy_enabled: false

server:
  http_listen_port: 9009
  grpc_listen_port: 9095
  log_level: warn

common:
  storage:
    backend: filesystem
    filesystem:
      dir: /data/mimir

blocks_storage:
  backend: filesystem
  bucket_store:
    sync_dir: /data/mimir/tsdb-sync
  filesystem:
    dir: /data/mimir/tsdb
  tsdb:
    dir: /data/mimir/tsdb-head

compactor:
  data_dir: /data/mimir/compactor
  sharding_ring:
    kvstore:
      store: memberlist

distributor:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist

ingester:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist
    replication_factor: 1
    min_ready_duration: 0s

store_gateway:
  sharding_ring:
    replication_factor: 1

limits:
  native_histograms_ingestion_enabled: true
