apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    uid: loki
    url: http://loki:3100
    isDefault: false
    jsonData:
      derivedFields:
        - name: TraceID
          matcherRegex: "trace_id"
          matcherType: label
          datasourceUid: tempo
          urlDisplayLabel: View Trace
        - name: TraceExplorer
          matcherRegex: "trace_id"
          matcherType: label
          url: "/d/trace-to-logs-explorer/trace-to-logs-explorer?var-traceId=$${__value.raw}&from=now-1h&to=now"
          urlDisplayLabel: View in Trace Explorer

  - name: Tempo
    type: tempo
    access: proxy
    uid: tempo
    url: http://tempo:3200
    isDefault: false
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        filterByTraceID: true
        filterBySpanID: false
        lokiSearch: true
      tracesToMetrics:
        datasourceUid: mimir
      serviceMap:
        datasourceUid: mimir
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: loki

  - name: Mimir
    type: prometheus
    access: proxy
    uid: mimir
    url: http://mimir:9009/prometheus
    isDefault: true
    jsonData:
      prometheusType: Mimir
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: tempo

  - name: Tempo API (Infinity)
    type: yesoreyeram-infinity-datasource
    access: proxy
    uid: tempo-infinity
    jsonData:
      url: http://tempo:3200
